services:
  postgres:
    image: postgres:16
    container_name: library-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: librarydb
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d librarydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: library-api
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/librarydb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7e4a4c29f8be5bd0c2a8f52d0
      JWT_EXPIRATION: 86400000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data: